// automatically generated by the FlatBuffers compiler, do not modify

package com.google.flatbuffers;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;
public abstract class Union { 
  public abstract byte getUnionType();
  public abstract int build(FlatBufferBuilder builder);
}